--- 
- 
  gather_facts: false
  hosts: nodes
  pre_tasks: 
    
    - name: "Install python2"
      yum: 
        name: python
        state: latest
    
    - name: "Install NetworkManager"
      yum: 
        name: NetworkManager
        state: latest
    
  
  tasks: 
    
    - name: "Install Docker"
      retries: 3
      yum: 
        name: docker
        state: latest

    - name: "Enable NetworkManager"
      service:
        name: NetworkManager
        state: started
   
    - name: "Enable docker"
      service:
        name: docker
        state: started
   
    - name: "Add repository"
      yum_repository: 
        baseurl: "https://rpms.svc.ci.openshift.org/openshift-origin-v3.11/"
        description: "OKD 311 repo"
        gpgcheck: false
        name: okd
