
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "artifactory"
spec:
  source:
    contextDir: Jenkins/Artifactory/
    git: 
      uri: "https://github.com/AmirSedrak/test"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsFilePath: Jenkins/Artifactory/Jenkinsfile
