def mvnCmd = "mvn"



pipeline {
     agent {
      node {
        label 'maven'
      }    
    }

    // Global tools to be used
 //   tools {
 //       maven 'maven3.6' 
 //       jdk 'jdk8' 
//    }

    stages {
        stage('Pull App') {
          steps {
            git branch: 'master', url: "https://github.com/javaparser/javaparser-maven-sample.git"
          }
        }
               
        stage ('Artifactory configuration') {
            steps {
        script {
          sh "${mvnCmd} clean install"
                }
             }  
        }

     //   stage ('Build & Upload Artifact') {
      //      steps {
                
                // run Maven Build and upload the built artifact to Artifactory
        //        rtMavenRun (
          //          pom: 'maven-example/multi2/pom.xml',
          //          goals: 'clean install',
        //        )
      //      }
      //  }
        
        
        
        
        
       stage ('Build & Upload Artifact') {
            steps {
                
                // run Maven Build and upload the built artifact to Artifactory
                rtMavenRun (
                    pom: 'maven-example/multi2/pom.xml',
                    goals: 'clean install',
                )
            }
        }
        
        
        
        stage ('Publish build info') {
            steps {
                rtPublishBuildInfo (        
                    serverId: "ARTIFACTORY_SERVER"
                )
            }
        }
    }
}
