kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "ci-cd-java-pipeline"
spec:
  source:
    git: 
      uri: "https://github.com/AmirSedrak/test"
  strategy:
    jenkinsPipelineStrategy:
      type: JenkinsPipeline
