
pipeline {
  agent {
              node {
                  label 'nodex'
              }
            } 
  stages {
    stage('Pull App') {
      steps {
        git branch: 'master', url: 'https://github.com/AmirSedrak/frontend.git' 
      }
    }
  
    
      stage('Install dependencies') {
      steps {
          steps {
                    sh 'npm install'
                }
      }  
    }
    
      stage('Build Application') {
                    steps {
                        sh "npm run ng build"
                    }
                }
    
    
    
     stage('Code Analysis') {
      steps {
        script {
          sh "sonar:sonar  \
            -Dsonar.projectKey='javascript-backend' \
            -Dsonar.projectName='javascript-backend' \
            -Dsonar.sources=. \
            -Dsonar.host.url='http://sonarqube.pipeline.svc:9000' \
            -Dsonar.login='admin' \
            -Dsonar.password='admin'"
        }
      }
    }
    
    stage('Build on Test') {
      steps {
        script{
            openshiftDeploy apiURL: '', authToken: '', depCfg: 'nodejs', namespace: 'pipeline', verbose: 'false', waitTime: '', waitUnit: 'sec'
        }
      }
    }
    
    stage('Deploy to Test') {
      steps {
        script{
            openshiftDeploy apiURL: '', authToken: '', depCfg: 'nodejs', namespace: 'pipeline', verbose: 'false', waitTime: '', waitUnit: 'sec'
        }
      }
    }  
  }
}
