
pipeline {
  agent {
              node {
                  label 'node'
              }
            } 
  stages {
    stage('Pull App') {
      steps {
        git branch: 'master', url: 'https://github.com/AmirSedrak/frontend.git' 
      }
    }
  
    
      stage('Install dependencies') {
      steps {
          steps {
                    sh 'npm install'
                }
      }  
    }
    
      stage('Build Application') {
                    steps {
                        sh "npm run ng build"
                    }
                }
    
    
    

    
    stage('Build on Test') {
      steps {
        script{
            openshiftDeploy apiURL: '', authToken: '', depCfg: 'nodejs', namespace: 'pipeline', verbose: 'false', waitTime: '', waitUnit: 'sec'
        }
      }
    }
    
    stage('Deploy to Test') {
      steps {
        script{
            openshiftDeploy apiURL: '', authToken: '', depCfg: 'nodejs', namespace: 'pipeline', verbose: 'false', waitTime: '', waitUnit: 'sec'
        }
      }
    }  
  }
}
